/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'koray' at '11/13/16 4:53 PM' with Gradle 2.8
 *
 * @author koray, @date 11/13/16 4:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
